---
title: "Temporally-varying water use strategies in *Juniperus osteosperma* associated with GPP"
author: 
 - Jessica S. Guo:
    email: jessicaguo@email.arizona.edu
    institute: [UArizona]
    correspondence: true
 - Steven Kannenberg:
    institute: [CSU]
    correspondence: false
 - Mallory Barnes:
    institute: [IU]
    correspondence: false
 - William R.L. Anderegg:
    institute: [UU]
    correspondence: false
    
institute:
  - UArizona: Arizona Experiment Station, University of Arizona, Tucson, Arizona
  - CSU: Department of Biology, Colorado State University, Fort Collins, Colorado
  - IU: O'Neill School of Public and Environmental Affars, Indiana University, Bloomington, Indiana
  - UU: School of Biological Sciences, University of Utah, Salt Lake City, Utah

output: 
    bookdown::word_document2:
      number_sections: no
      fig_caption: yes
      reference_docx: "templates/template.docx"
      pandoc_args:
      - --lua-filter=templates/scholarly-metadata.lua
      - --lua-filter=templates/author-info-blocks.lua
linkcolor: black
bibliography: refs.bib
link-citations: yes
csl: "templates/new-phytologist.csl"

keywords: |
  keyword1; keyword2; keyword3
  
editor_options:
  markdown:
    wrap: sentence
    canonical: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\pagebreak

### Summary

-   Some plants exhibit temporally flexible hydraulic regulation, wherein the strictness of hydraulic control (e.g., iso/anisohydry) change in response to environmental conditions, but the implications of flexible hydraulic behavior for plant productivity is unknown.
    The temporal responses of hydraulic behavior and gross primary productivity (GPP) were evaluated for *Juniperus osteosperma*, a semi-arid woodland conifer considered relatively drought resistant.

-   Using a 5-month growing season timeseries of *in situ* plant water potential ($\Psi$) and GPP, the stringency of hydraulic regulation and plant productivity were explored relative to soil water availability and atmospheric demand.

-   *J. osteosperma* experiences weaker hydraulic regulation and higher productivity after monsoon precipitation pulses, when soil moisture water and atmospheric demand are both high.
    The relationship between $\Psi_{PD}$ and $\Psi_{MD}$ ($\sigma$) is strongly correlated with GPP, although only during the monsoon period.
    Interestingly, GPP response more rapidly to moisture inputs than $\sigma$.

-   Flexible hydraulic regulation appears to allow *J. osteosperma* to prolong the period of high carbon uptake following episodic rain events during the growing season.
    While the underlying physiological mechanisms that allow for temporal adjustment need further study, this flexibility can partially explain the success of some drought-tolerant species and suggests why dynamic vegetation models often underestimate the productivity of semi-arid ecosystems.

\pagebreak

### Introduction

Plant water use strategies encompass the numerous ways plants have evolved to confront an inescapable dilemma: obtaining the raw materials for photosynthesis necessitates water loss through stomata [@berry2010]. Along the soil-plant-atmosphere continuum, gradients of water potential ($\Psi$) drive water transport and integrate the tradeoff between carbon gain and water loss, such that the popular iso/anisohydry spectrum is based on the stomatal regulation of $\Psi$ [@tardieu1998; @jones1998]. Isohydry describes a conservative strategy of stomatal closure to maintain $\Psi$ above a threshold to preserve hydraulic conductivity, while anisohydry is a profligate stomatal strategy that prioritizes carbon gain at the expense of low $\Psi$. While entire species have been placed on the iso/anisohydry spectrum, recent work has demonstrated that multiple strategies can occur within a species, which results from plant-environment interactions in accordance with hydraulic theory [@hochberg2018]. Within species shifts in iso/anisohydry have been reported for *Larrea tridentata* [@guo2020] and *Quercus douglasii* [@feng2019] in different seasons, in *Quercus suber* due to competition [@haberstroh], *Acacia aptaneura* as a result of repeated experimental drought [@nolan2017], and in multiple species between wet and dry years [@wu2021].

However, the C implications of temporally-variable hydraulic strategies are not well understood, even as they become more important for forecasting and ameliorating the effects of climate change [@novick2022; @kennedy2019]. In the semi-arid climate where these dynamic hydraulic strategies are found, persistent water limitation and episodic precipitation promote tight coupling between carbon and water cycles [@biederman2016], resulting in added temporal complexity that can be difficult to model [@ogle2004; @noy-meir1973; @loik2004; @feldman2018]. Semi-arid ecosystems are largely responsible for the interannual variability of the global carbon sink [@poulter2014; @ahlstrom2015], including rapid vegetation expansion associated with wet years, yet dynamic global vegetation models are prone to underestimating C uptake in dryland regions [@macbean2021].
Understanding the temporal dynamics and environmental sensitivity of plant hydraulic strategies may be critical to improving predictive forecasts of the global carbon cycle.

Drought-induced mortality in pinyon-juniper woodlands is an iconic consequence of climate change in the southwestern US.
Pinyon mortality following the 2002-2003 drought was associated with differences in plant hydraulic regulation [@breshears2009; @plaut2012]; juniper survival was largely attributed to less hydraulically vulnerable xylem and thus greater ability to withstand low water potentials [@mcdowell2008].
Although generally considered anisohydric, *Juniperus monosperma* exhibited strong stomatal control and negligible xylem embolism under drought manipulation [@garcia-forner2016], thus challenging the paradigm of anisohydric species being prone to hydraulic failure.
As the southwestern US megadrought persists [@williams2022] and induces mortality even among resilient *Juniperus* spp.
[@kannenberg2021], it is imperative to probe how anisohydryic strategies interact with plant productivity and survival.

In this study, we utilize a five month time-series of plant $\Psi$ and ecosystem C fluxes in a juniper woodland to evaluate the relationship and temporal dynamics between hydraulic strategy and gross primary productivity (GPP).
We ask:

1)  Does plant hydraulic regulation vary over time in *J. osteosperma*?
2)  How do the environmental drivers and their timescales of influence compare between plant hydraulic strategy and GPP?
3)  What is the relationship between hydraulic strategy and GPP over a growing season?

We believe this is one of the first studies to contemporaneously measure plant $\Psi$ and GPP at daily temporal resolution, which permits direct investigation of the implications of $\Psi$ regulation for productivity in an iconic southwestern species.

### Materials and Methods

This study was conducted at an early-successional pinyon-juniper woodland (37.5241 N, 109.7471 W, 1866 m a.s.l.) in southeastern Utah.
Local climate conditions include cold winters and hot, dry summers, with high interannual variability in summer precipitation due to its location at the northern boundary of the North American Monsoon.
The locally flat topography is dominated by Utah juniper (*Juniperus osteosperma*, 92% tree basal area) and two-needle pinyon (*Pinus edulis*, 8% tree basal area), with sparse understory comprising big sagebrush (*Artemisia tridentata*), prickly pear cactus (*Opuntia* spp.), and bunchgrasses.
See Kannenberg et al. in review for more site details.

#### Eddy covariance and environmental variables

An eddy covariance flux tower (AmeriFlux US-Cdm) was deployed in June 2019 to measure fluxes of water, carbon, and energy and to monitor site-level meteorological and soil variables [@kannenberg2022].
The sonic anemometer (Campbell Scientific CSAT3), open-path infrared gas analyzer (Campbell Scientific EC150), and temperature/relative humidity sensor (Vaisala HMP155) were installed at a height of 8 m, while the net radiometer (Kipp and Zonen CNR4) and photosynthetic photon flux density sensor (Kipp and Zonen PQS1) were installed at a height of 6.45 m.
Site precipitation was measured with a tipping bucket rain gauge (Campbell Scientific TE535WS), while volumetric water content and temperature of the soil were monitored with five sensors (Acclima TDT) deployed at depths of 5 cm, 10 cm, 20 cm, 50 cm, and 100 cm.
See Kannenberg et al. in review for additional details on calibration and maintenance.

Eddy covariance and environmental data were processed first by summarizing to half-hourly values, gapfilling, and then summarizing to daily values used the the subsequent figures and analysis.
High frequency eddy covariance data were processed into half-hourly values of net ecosystem exchange (NEE) using *EasyFlux PC* (Campbell Scientific) following a procedure of despiking [@vickers1997], coordinate rotation, spectral correction [@massman2000], and Webb-Pearman-Leuning density correction [@webb1980].
NEE was gap-filled using the 50th percentile Ustar distribution and partitioned into gross primary productivity (GPP) and ecosystem respiration using the nighttime method [@reichstein2005] in the R package 'REddyProc' [@wutzler2018].
All environmental variables were summarized to half-hourly means or sums where appropriate; air temperature, vapor pressure deficit, and incoming shortwave radiation were gap-filled using the MDS algorithm [@reichstein2005].
Ecosystem fluxes and precipitation were aggregated to daily sums, vapor pressure deficit was summarized to daily maximums, and the remaining environmental variables were summarized as daily means.

#### Plant water potential

Stem water potential of seven mature *J. osteosperma* within the tower footprint (\< 20 m) were monitored with both automated and manual measurements between May 24 and November 5, 2021.
Half-hourly water potential was monitored with stem psychrometers (ICT International PSY1) that were calibrated prior to installation.
Two instruments were installed per tree by removing the bark and phloem to expose a flat xylem surface.
Psychrometer sensor heads were attached with self-adhesive silicone tape to maintain a tight seal and wrapped in reflective insulation to minimize temperature gradients.
Because plant wounding responses can fill the sensor chamber, each psychrometers was uninstalled, cleaned with chloroform, and reinstalled on a new branch every 4-5 weeks.
The day after reinstallation, xylem water potential was measured manually with a Scholander-type pressure chamber (PMS 610) by excising a needle cluster with diameter between 2 and 4 mm and measuring within \_\_ minutes of collection.

Half-hourly stem water potential time series were subject to quality control by visual assessment and processed to daily values.
After removing data during the maintenance period (+ 1 day) and outliers that were \> 0.5 MPa way from adjacent points, data that met the following criteria were also discarded: 1) a step change in the magnitude of water potential not attributable to a precipitation event; 2) loss of diurnal pattern in water potential.
On average, data from 10 of 14 psychrometers were available during a given period.
Half-hourly stem water potential was summarized to predawn ($\Psi_{PD}$, 2 hours prior to sunrise) and midday ($\Psi_{PD}$, 2 hours following solar noon) for each logger.

#### Model description - hydraulic regulation

To specify the hydraulic regulation model, we used the Martinez-Vilalta et al. [@martínez-vilalta2014] equation to relate $\Psi_{MD}$ to $\Psi_{PD}$:

$$
\begin{equation}
\tag{1}
\Psi_{MD} = \sigma \cdot \Psi_{PD} + \lambda
\end{equation}
$$

where $\sigma$ represents the stringency of hydraulic regulation and $\lambda$ describes the pressure drop when soil moisture is not limiting.
Plant hydraulic regulation can be described as isohydry if \$\\sigma \< 1\$, anisohydry if \$\\sigma \\approx 1\$, and extreme anisohydry if $sigma > 1$.

To allow hydraulic regulation and GPP to vary over the growing season, we specified a hierarchical Bayesian model that estimated $\sigma$, $\lambda$, GPP as linear functions of maximum daily vapor pressure deficit ($D$) and volumetric soil water content at 10 cm (\$W\_{10}\$).
Furthermore, we implemented the stochastic antecedent model [@ogle2015] to quantify the influence of past environmental conditions.
The data model for hydraulic regulation describes the likelihood of each observed \$\\Psi\_{MD}\$, which was normally distributed for each observation $i$ ($i = 1, 2, \ldots, 1425$):

$$
\begin{equation}
\tag{2}
{\Psi_{MD}}_i \sim Normal({{\overline{\Psi}}_{MD}}_i, \sigma_{\Psi}^2)
\end{equation}
$$

where ${{\overline{\Psi}}_{MD}}_i$ is the predicted or mean midday water potential and $\sigma_{\Psi}^2$ represents the observation variance.
${{\overline{\Psi}}_{MD}}_i$ was modeled according to Eqn 1, where all terms were allowed to vary over time, either as direct observations (\$\\Psi\_{MD}\$,\$\\Psi\_{PD}\$) or as modeled parameters (\$\\sigma\$, $\lambda$).
The time-varying estimates of hydraulic regulation, $\sigma$ and $\lambda$ were indexed by $i$ and modeled as linear combinations of two antecedent covariates and their interaction:

$$
\begin{equation}
\tag{3}
\sigma_i = \beta_0 + \beta_1 \cdot D_i^{ant} + \beta_2 \cdot {W_{10}}_i^{ant} + \beta_3 \cdot D_i^{ant} \cdot {W_{10}}_i^{ant} + \mathcal{E}_{\sigma, t(i)}\\
\lambda_i = \alpha_0 + \alpha_1 \cdot D_i^{ant} + \alpha_2 \cdot {W_{10}}_i^{ant} + \alpha_3 \cdot D_i^{ant}\cdot {W_{10}}_i^{ant} + \mathcal{E}_{\lambda, t(i)}
\end{equation}
$$

The $\beta$ and $\alpha$ parameters were estimated for all trees.
$\mathcal{E}_{\sigma}$ and $\mathcal{E}_{\lambda}$ represent the random effects of each tree, where $t(i)$ indicates tree $t$ associated with each observation \$i\$.
$D_{max}$ and $W_{10}$ were scaled using the 2021 mean and standard deviation so that regression coefficients could be compared and $\beta_0$ and $\alpha_0$ could be interpreted as $\sigma$ and $\lambda$, respectively, under mean environmental conditions.
Antecedent variables [@ogle2015] were constructed using daily time series of each scaled environmental variable:

$$
\begin{equation}
\tag{4}
D_i^{ant} = \sum_{p = 0}^{T_{lag}}\omega_{D_p} \cdot D_{t(i)-p}\\
{W_{10}}_i^{ant} = \sum_{p = 0}^{T_{lag}}\omega_{W_p} \cdot W_{t(i)-p}
\end{equation}
$$

where $p$ indicates the time step, $T_{lag}$ represents the total number of past time-steps considered, $\omega_{D_p}$ and $\omega_{W_p}$ indicates the weight or relative importance of the \$p\$th time step into the past, and $D_{t(i)-p}$ and $W_{t(i)-p}$ are the observed value of each variable at $p$ time steps ago.
Antecedent covariates are weighted averages of past covariate values where the weights are stochastically determined by the data.
In this analysis, $D^{ant}$ was constructed using daily values from the current day to 4 days ago ($p$ = 1, $T_{lag}$ = 5), while $W_{10}^{ant}$ was constructed using three-day averages of $W_{10}$ from the current day to 20 days ago ($p$ = 3, $T_{lag}$ = 7).

In order to complete this model, a zero-centered hierarchical normal prior was specified for tree random effects:

$$
\begin{equation}
\tag{5}
\mathcal{E}_{\sigma, t} \sim Normal(0, \sigma_{\sigma}^2)\\
\mathcal{E}_{\lambda, t} \sim Normal(0, \sigma_{\lambda}^2)
\end{equation}
$$ where reparameterization by sweeping was employed to ensure identifiability between the intercepts ($\beta_0$, $\alpha_0$) and the random effects [@vines1996].

All remaining parameters were given standard priors following Gelman et al. [-@gelman2014].
The regression coefficients were assigned relatively non-informative normal priors centered at zero with large variance.
Antecedent importance weights, vectors of length $T_{lag}$ (Eqn 4), were given non-informative Dirichlet priors that assume *a priori* that each past time step has equal importance, and that constrain weights for each covariate to sum to 1 across all time steps, \$p\$.
The standard deviation of tree random effects (\$\\sigma\_{\\sigma}\$ and \$\\sigma\_{\\lambda}\$) were given relatively non-informative $Uniform(0, 1)$ priors, while the measurement error precision (\$1/\\sigma\_{\\Psi}\^2\$) was assigned a conjugate, relatively non-informative $Gamma(0.1, 0.1)$ prior.

#### Model description - GPP

Similarly, the data model for daily ecosystem productivity describes the likelihood of each observed \$GPP\$, which was normally distributed for each observation $j$ ($i = 1, 2, \ldots, 166$):

$$
\begin{equation}
\tag{4}
{GPP}_j \sim Lognormal(\overline{GPP}_j, \sigma_{GPP}^2)
\end{equation}
$$

where $\overline{GPP}_j$ is the predicted or mean daily GPP and the variance $\sigma_{GPP}^2$ represents the uncertainty in observed $GPP$.
$\overline{GPP}_j$ was modeled as a linear function of the same antecedent covariates and interaction as in Eqn 3.

$$
\begin{equation}
\tag{5}
\overline{GPP}_j = \gamma_0 + \gamma_1 \cdot {D_{max}}_j^{ant} + \gamma_2 \cdot {W_{10}}_j^{ant} + \gamma_3 \cdot {D_{max}}_j^{ant}\cdot {W_{10}}_j^{ant}
\end{equation}
$$

Antecedents weights were constructed identically to Eqn 4, with the weights determined by the GPP data.

#### Model implementation and interpretation

The above models were implemented in JAGS 4.3.0 [@plummer2003] using R 4.1.1 and 'rjags' 4.13 [@rcoreteam2021, @plummer2022].
For each model, three parallel Markov chain Monte Carlo sequences were initiated with dispersed starting values; initial iterations were run until model convergence, as indicated by the Gelman and Rubin [@gelman1992] statistic.
Models were then run for 150,000 iterations and thinned by 50 to reduce within-chain autocorrelation and storage requirements, yielding a total of 9000 relatively independent posterior samples for each quantity of interest, including the regression coefficients and antecedent weights.
Posterior distributions were summarized by their means and 95% highest posterior density credible intervals (henceforth, 95% CIs).
Covariate effects were significant if the 95% CI did not overlap zero.
To quantify seasonal variation in \$\\sigma\$, the posterior samples of the $\beta$ regression coefficients and antecedent weights were combined with the time-series of scaled $D_{max}$ and $W_{10}$ to produce posterior means and 95% CIs.

### Results

#### Seasonal dynamics of $\Psi$

The

#### Environmental drivers and timescales of $\sigma$ and GPP

The

#### Relationship between $\sigma$ and GPP

The

### Discussion

### Acknowledgements

### Author contributions

### Data availability

### Tables

### Figures

\pagebreak

### References
